- .npmrc
Исправляет ошибку при попытке сделать npm release (используется внутри semantic-release)
> chore(npm): ignore workspaces by npm

- packages/arui-scripts/src/configs/webpack.client.ts
Исправление небольшой ошибки в том, как определяется NODE_ENV переменная. В прод режиме ее всегда сам определяет вебпак, для дев режима ранее был вот такой https://github.com/core-ds/arui-scripts/blob/v14.0.0/packages/arui-scripts/src/configs/webpack.client.prod.ts#L310 костыль.
Не хочется давать возможность определять кастомный NODE_ENV для продакшен сборок, но для дев режима, чтобы не ломать совместимость, эту возможность лучше оставить.
> fix(webpack-client): add NODE_ENV variable in dev mode

- packages/arui-scripts-test/package.json
- packages/arui-scripts/src/configs/webpack.client.ts
Если в arui-scripts start всегда используется dev-конфиг, то имеет смысл сделать скип проверки NODE_ENV для react-refresh-/babel
> fix(webpack.client.ts): fix #13

- packages/arui-scripts/package.json
- yarn.lock
Апдейт fork-ts-checker до версии 6.5.3, чтобы не было варнингов при typescript@5
> chore(*): fix #23

- .github/workflows/alpine-node.yml
Новый buildx выдает образы в формате, не совместимом с docker 1.13.0, который, к сожалению, используется на части наших серверов
> fix(docker): chagne output format for docker build to support older client

- packages/arui-scripts/src/configs/webpack.client.ts
В какой то момент времени мы потеряли эту оптимизацию сборки. moment.js все еще используется на ряде проектов, при этом он несет с собой огромное кол-во кода локализаций. 
Фиксим это, выкидывая их из сборки вебпака.
> feat(webpack): ignore momentjs locales

- packages/alpine-node-nginx/nginx.conf
Возникла необходимость сжимать gzip'ом wasm файлы предоставляемые библиотекой Smart Engines, которую мы используем для распознавания изображений
> feat(*): compress wasm with gzip

- packages/alpine-node-nginx/nginx.conf
После обсуждения решили сжимать при помощи brotli вместо gzip т.к. сжимает эффективнее + возможно, настройка `gzip_types  application/wasm;` могла переопределять какие-то дефолтные типы для gzip сжатия.
Ревертнул настройку для gzip, добавил соответствующий тип файла для brotli
> feat(*): compress wasm with brotli

- packages/arui-scripts/package.json
- packages/arui-scripts/src/configs/webpack.client.ts
- yarn.lock
Добавление плагина для улучшенной дедупликации зависимостей.
**В чем суть плагина?**
Дедупликация yarn или npm не всесильна. Рассмотрим такую ситуацию:
Проект зависит от `lodash@1`, `library1`, `library2`. 
`library1` и `library2` зависят от `lodash@2`. Дерево зависимостей в таком случае будет выглядеть так:
```bash
node_modules
lodash # 1.1.1
library1
node_modules
lodash # 2.2.2
library2
node_modules
lodash # 2.2.2
```
`lodash@2` будет в нашем дереве дважды, и у пакетного менеджера нет никаких вариантов их дедуплицировать. В бандл таким образом будут попадать сразу 2 одинаковых версии lodash@2.
Этот плагин лечит эту проблему, позволяя убрать до 10% parsed размера кода. (для gzip все не на столько впечетляюще, всего 1%, но на то он и gzip чтобы хорошо сжимать дублируемый код).
Реализация …
> feat(webpack): add deduplication plugin

- .changeset/four-eels-own.md
- packages/arui-scripts/src/commands/build/build-wrapper.ts
- packages/arui-scripts/src/commands/build/client.ts
- packages/arui-scripts/src/commands/bundle-analyze/index.ts
- packages/arui-scripts/src/commands/util/make-tmp-dir.ts
- packages/arui-scripts/src/commands/util/run-client-dev-server.ts
Попытка разбить пул-реквест с модулями на чуть более мелкие и понятные части. Этих пул-реквестов будет несколько последовательно.
Добавляем поддержку работы с множеством конфигов вебпака. Позволяет нормально выводить информацию о сборке в консоль и фиксит работу команды bundle-analyze.
> fix(bundle-analyze): allow bundle analyzer to work with multiple configs

- .changeset/fuzzy-boxes-juggle.md
- packages/arui-scripts-test/arui-scripts.overrides.ts
- packages/arui-scripts-test/src/client.tsx
- packages/arui-scripts-test/src/worker.ts
- packages/arui-scripts/README.md
- packages/arui-scripts/src/configs/postcss.config.ts
- packages/arui-scripts/src/configs/process-assets-plugin-output.ts
- packages/arui-scripts/src/configs/util/__tests__/apply-overrides.tests.ts
- packages/arui-scripts/src/configs/util/apply-overrides.ts
- packages/arui-scripts/src/configs/webpack.client.dev.ts
- packages/arui-scripts/src/configs/webpack.client.prod.ts
- packages/arui-scripts/src/configs/webpack.client.ts
- packages/arui-scripts/src/index.ts
Попытка разбить пул-реквест с модулями на чуть более мелкие и понятные части. Этих пул-реквестов будет несколько последовательно.
Этот пр приносит более удобный способ создавать сразу несколько конфигураций для вебпака, функцию `createSingleWebpackConfig`. Она будет использоваться внутри в дальнейшем для того чтобы делать конфигурацию для модулей, но так же может быть использована пользователями для создания своих кастомных конфигураций, которые билдят сразу несколько независимых бандлов из одного проекта
> feat(webpack): add createSingleWebpackConfig method

- .github/workflows/snapshot-release.yml
Исправление воркфлоу для выпуска пререлизов, черепик из ветки с модулями
> ci(prerelease): pass gh token to snapshot action

- .changeset/brown-dots-explain.md
- packages/arui-scripts-test/package.json
- packages/arui-scripts/README.md
- packages/arui-scripts/package.json
- yarn.lock
Мотивация
---
Как описано в #46, при попытке установить `arui-scripts` в закрытом контуре, сборка падает с ошибкой. Причина в том, что ряд `imagemin`-плагинов после установки стучится в сеть для скачивания бинарников, которые выполняют непосредственную работу по оптимизации изображений (`cjpeg` и пр.). Для того, чтобы как можно быстрее исправить эту проблему и позволить устанавливать последние версии `arui-scripts`, данные плагины вынесены в `peerDependencies`. Теперь они не будут установлены при обычной установке пакетов. Это не касается оптимизации `svg`, которая не требует дополнительных бинарников и по-прежнему работает.
Чтобы иметь возможность воспользоваться `imagemin`-плагинами, необходимо установить их в свой проект, а также предпринять меры по доступности всех необходимых файлов …
> fix(*): move imagemin plugins to peer deps

- .changeset/moody-ladybugs-fold.md
- packages/arui-scripts/src/configs/postcss.config.ts
- packages/example/src/components/app.module.css
Исправление некорректной конфигурации для postcss. Видимо тут https://github.com/core-ds/arui-scripts/pull/38/files немного это поломалось, и вылезало сразу два бага:
- Не добавлялись custom-media по дефолту (--tablet, --desktop и тд)
- Не выпиливались css переменные если настройка keepCssVars была выставлена в false
> fix(postcss): always add custom media variables

- .changeset/afraid-kids-sneeze.md
- packages/arui-scripts/src/configs/modules.ts
Небольшое изменение сборки css для модулей. Раньше, если флаг keepCssVars был равен true, css переменные которые не используются в хост-проекте не добавлялись в бандл, а в модуле эти переменные добавлялись с префиксом, например так:
```
.some-module-prefix :root {
--some-variable: 100500px;
}
```
Такой синтаксис не работает из-за чего в браузере в модулях ломалась верстка.
Чтобы этого избежать была добавлена функция transform, которая меняет объявление переменных. Теперь переменные будут объявляться в контексте префикса вот так:
```
.some-module-prefix {
--some-variable: 100500px;
}
```
В таком случае данные переменные будут доступны только внутри класса `.some-module-prefix` и не повлияют на стили хост-приложения.
> fix(module): postcss prefix for css root variables

- .changeset/young-parrots-push.md
- packages/arui-scripts-modules/src/module-loader/create-module-fetcher.ts
- packages/arui-scripts-modules/src/module-loader/hooks/use-module-factory.ts
- packages/arui-scripts-modules/src/module-loader/hooks/use-module-loader.ts
- packages/arui-scripts-modules/src/module-loader/hooks/use-module-mounter.ts
- packages/arui-scripts-modules/src/module-loader/index.ts
- packages/arui-scripts-modules/src/module-loader/types.ts
- packages/arui-scripts-server/src/modules/__tests__/create-get-modules-method.tests.ts
- packages/arui-scripts-server/src/modules/create-get-modules-method.ts
- packages/arui-scripts-server/src/modules/types.ts
- packages/arui-scripts/docs/modules.md
- packages/example-modules/arui-scripts.config.ts
- packages/example-modules/src/modules/factory-module-compat/index.ts
- packages/example-modules/src/modules/server-state-factory-module/index.ts
- packages/example-modules/src/server/index.ts
- packages/example/src/components/modules-tabs.tsx
- packages/example/src/module-mounters/factory-compat-module-mounter.tsx
- packages/example/src/module-mounters/server-state-factory-module-mounter.tsx
1. Добавил модули-фабрики. Смысл в том, чтобы можно было использовать стейт модулей (серверный, клиентский) для создания этих же модулей, как например это происходит в монтируемых модулях, но чего нет в абстрактных.
2. Добавил в стейт модуля hostAppId по умолчанию, чтобы им так же можно было воспользоваться
> Module update

- .changeset/tidy-apes-sleep.md
- packages/arui-scripts-modules/src/module-loader/hooks/use-module-factory.ts
Небольшой фикс для хука useModuleFactory. Т.к. фабрика может вернуть функцию, то логично использовать callback для setState.
> Fix modules

- .changeset/long-poems-end.md
- packages/arui-scripts/src/configs/app-configs/__tests__/update-with-package.tests.ts
- packages/arui-scripts/src/configs/app-configs/update-with-config-file.ts
- packages/arui-scripts/src/configs/app-configs/update-with-env.ts
- packages/arui-scripts/src/configs/app-configs/update-with-package.ts
- packages/arui-scripts/src/configs/app-configs/update-with-presets.ts
Правильным образом мержим конфигурации сложной формы. Это может быть полезно для пресетов меняющих настройки сложных полей конфига, типа модулей, настроек прокси или минификаторов картинок.
> fix(settings): correctly merge complex settings

- .changeset/sour-walls-march.md
- packages/arui-scripts/package.json
- packages/arui-scripts/src/configs/modules.ts
- packages/example-modules/src/modules/module-compat/index.ts
- packages/example-modules/src/modules/module-compat/styles.css
- yarn.lock
Обновление postcss изменило то, как работает postcss-prefix-selector. Теперь он стал запускаться и для nested селекторов, что приводило к генерации некорректного css.
Например для такого css:
```css
.foo {
color: red;
&__bar {
color: blue;
}
}
```
генерировался код:
```css
.module-example .foo {
color: red;
}
.module-example .module-example .foo__bar {
color: blue;
}
```
Фиксим это
> fix(compat-modules): correctly add css prefixes for nested selectors

- package.json
- packages/example-modules/arui-scripts.overrides.ts
- packages/example-modules/jest.config.validate-build.js
- packages/example-modules/package.json
- packages/example-modules/validate-build/__snapshots__/build.spec.ts.snap
- packages/example-modules/validate-build/build.spec.ts
- packages/example-modules/validate-build/tsconfig.json
- turbo.json
Добавлен простенький механизм валидации билда для проекта example-modules.
Проверяет что после билда создаются все нужные файлы + что файлы выглядят так, как надо.
Пока не уверен что это реально полезные тесты, которые помогут находить проблемы, поэтому проверяют они очень немногое.
Эти тесты теперь зависят от того, чтобы проект был собран перед тем как тесты запустились. Это конечно плохо, но в целом решается просто запуском всего и вся через turbo, в котором все эти зависимости описаны
> test(example-modules): add some validation for build

- .changeset/twelve-monkeys-collect.md
- packages/arui-scripts/src/configs/webpack.client.ts
При сборке с использованием lazy-импортов выводятся предупреждения:
```
Conflicting order. Following module has been added:
* ...gutters.css
despite it was not able to fulfill desired ordering with these modules:
* ...inverted.css
- couldn't fulfill desired order of chunk group(s) root-page
- while fulfilling desired order of chunk group(s) settings-page
```
Проблема кроется в mini-css-extract-plugin и решается добавлением свойства [ignoreOrder](https://github.com/facebook/create-react-app/issues/5372#issuecomment-995632657)
> feat(*): ignore css order to prevent conflicts

- .changeset/curvy-fireants-tell.md
- packages/arui-scripts-modules/README.md
- packages/arui-scripts-modules/src/module-loader/hooks/use-module-factory.ts
- packages/arui-scripts-modules/src/module-loader/index.ts
- packages/arui-scripts-modules/src/module-loader/types.ts
Добавлен экспорт функции executeModuleFactory для использования модулей фабрик вне react-хуков.
Чутка поправлена документация, в ней использовались некорректные типы состояния загрузки
> docs(modules): add misising method, fix incorrect types

- .changeset/famous-hounds-compete.md
- packages/arui-scripts/.eslintrc.js
- packages/arui-scripts/docs/overrides.md
- packages/arui-scripts/src/configs/util/__tests__/find-plugin.tests.ts
- packages/arui-scripts/src/configs/util/apply-overrides.ts
- packages/arui-scripts/src/configs/util/find-plugin.ts
- packages/arui-scripts/src/configs/webpack.client.dev.ts
- packages/arui-scripts/src/configs/webpack.client.prod.ts
- packages/arui-scripts/src/configs/webpack.server.dev.ts
- packages/arui-scripts/src/configs/webpack.server.prod.ts
Появился findPlugin, который по аналогии с апишкой findLoader позволяет искать и менять конфиги плагинов
Вопросы:
1) Нужно ли такое вообще? (если не брать мастеров-оверрайдеров)
2) в оверрайдах клиента и сервера затипизировал так, чтобы в вызове плагина из webpackClient/Dev появлялись только клиентские плагины, а через webpackServer/Dev только серверные. Смущает немного реализация передачи дженерика внутрь хелпера, сделал через двойной вызов функции, по аналогии с typesafe-actions
Намеренно скипнул оверрайд WMF у клиента, а у сервера - HotModuleReplacementPlugin и NoEmitOnErrorsPlugin
> добавление findPlugin хелпера

- .changeset/fair-starfishes-wait.md
- packages/arui-scripts/src/configs/dev-server.ts
Фикс для devServer, который приходится сейчас локально переопределять в оверрайдах для корректной работы прокси на проектах, обновившихся до node18.
> fix(dev-server): use ipv4 host for proxy target

- .changeset/fast-wolves-deliver.md
- packages/arui-scripts/package.json
- packages/arui-scripts/src/configs/postcss.config.ts
- packages/arui-scripts/src/configs/supporting-browsers.ts
- packages/example-modules/validate-build/__snapshots__/build.spec.ts.snap
- packages/example/validate-build/__snapshots__/build.spec.ts.snap
- yarn.lock
**Ломающие изменения**
Выкидываем поддержку IE. Все основные направления его бросили, так что это безопасно делать. Обновление autoprefixer полностью исключает поддержку IE даже со стороны проектов - там просто выпилили те правила, которые к нему относились.
Так же исправлена работа с настройкой browsers - ранее css сборщик мог использовать другой конфиг. 
В плане изменения самих размеров бандлов - разница удивительно маленькая.
Очень большой проект, c total size 3.28 MB (776.44 KB gzip, 608.89 KB br)
похудел до 3.2 MB (771.7 KB gzip, 604.94 KB br). br стал всего на 4 кб меньше.
> feat(browserlist): drop IE support

- .changeset/shy-kiwis-crash.md
- packages/arui-scripts/src/plugins/arui-runtime/arui-runtime-module.ts
Исправлена проблема с запуском рантайм модуля на серверной стороне/рантайме без document. Там он запускаться не должен
> fix(webpack): don't run AruiRuntimeModule on server side

- packages/alpine-node-nginx/Dockerfile
- packages/alpine-node-nginx/Dockerfile-slim
В очередной раз чиним бинарные зависимости. Теперь то уж точно это должно быть последним?
libssl как оказалось идет в комплекте с самим алпайном, поэтому его нужно принудительно обновлять в любом случае
> fix(alpine-node-nginx): always upgrade all binary dependencies

- .changeset/nasty-humans-retire.md
- packages/arui-scripts/docs/settings.md
- packages/arui-scripts/src/configs/app-configs/index.ts
- packages/arui-scripts/src/configs/app-configs/types.ts
- packages/arui-scripts/src/configs/app-configs/warn-about-deprecations.ts
ts-loader помечен как deprecated. Когда то давно он был оставлен для совместимости со старыми проектами, сейчас же он создает больше проблем, чем приносит каких либо преимуществ.
babel-loader быстрее, лучше поддерживается и его можно использовать вместе с другими инструментами
> feat(tscLoader): mark as deprecated

- .changeset/thin-elephants-clap.md
- packages/arui-scripts-server/src/__tests__/read-assets-manifest.tests.ts
- packages/arui-scripts-server/src/read-assets-manifest.ts
readAssetsManifest некорректно обрабатывал ассеты, если их было несколько и лежали в массиве. Если script/style был массивом, то js.push/css.push добавлял их в результат также массивом, не разворачивая. Из за этого вид ответа был не string[], а string[][]
> fix(read-assets-manifest): fix processing assets array

- .changeset/wet-bikes-refuse.md
- packages/arui-scripts/jest-preset.js
Исправление прямого запуск jest'a
**Как сейчас?**
**Как должно быть?**
> fix(jest): fix jest-preset

- packages/arui-scripts/docs/overrides.md
После [этих изменений](https://github.com/core-ds/arui-scripts/pull/38/files#diff-7c23378b65dde6ab009174685b3ed9de92e89bdf9fcfa2d020bbc81ca95337eb) конфиг можно не пересоздавать.
> docs(overrides): remove obsolete way to config postcss

- .changeset/add-tsconfig-optional-chaining.md
- .gitignore
- packages/arui-scripts/src/configs/jest/settings.js
Происходит падение, если в tsconfig отсутствует поле compilerOptions.
Такое может быть в случае если tsconfig расширяется из другого места.
Ошибка:
```
tsConfigPaths = tsConfig.config.compilerOptions.paths || {};
^
TypeError: Cannot read properties of undefined (reading 'paths')
```
> fix(arui-scripts): add optional chaining for jest tsconfigs handler

- .changeset/flat-laws-exercise.md
- packages/arui-scripts/src/configs/modules.ts
Для 'compat' модулей, также как и для 'default' модулей настроен output.publicPath = 'auto' в конфиге webpack. Это позволит вебпаку автоматически определять, с какого урла загружать чанки модуля
> fix(modules): fixed output.publicPath for compat modules

- .changeset/thick-planes-sort.md
- packages/arui-scripts/package.json
- yarn.lock
Если сейчас обновится до последней версии arui-scripts, где есть swc, то поставится версия `@swc/core: 1.10` а с ней уже не работает `swc-plugin-coverage-instrument`
В консоль сыпит ошибки
`failed to invoke swc-plugin-coverage-instrument as js transform plugin at swc-plugin-coverage-instrument`
> fix(*): fixate swc/core version

- .github/workflows/alpine-node.yml
- packages/alpine-node-nginx/README.md
Обновление до последней LTS версии 22.14.0
в 22.13.1 в appsec есть уязвимости:
```
Уязвимость найдена в модуле libcrypto3@3.3.2-r1.
CVE: CVE-2024-12797.
```
```
Уязвимость найдена в модуле libssl3@3.3.2-r1.
CVE: CVE-2024-12797.
```
> feat(*): update nodejs to lts 22.14.0

- .github/workflows/alpine-node.yml
В текущих образах используется alpine 3.20.5 в которых есть уязвимости критичного уровня, на которые ругается апсек
https://hub.docker.com/layers/library/alpine/3.20.5/images/sha256-cbbabaca3bd3b2617ffff036d987a82bcfe923fd4bf985f338c12e74af1bd081
В частности CVE 2024-12797, который был исправлен в версии alpine 3.20.6
https://hub.docker.com/layers/library/alpine/3.20.6/images/sha256-367c8801047a3ab67a580e2ab142a2018d00e43b3573d81519a8f79576fbdbba
> feat(alpine-node): update alpine to 3.20.6

- .changeset/empty-hornets-burn.md
- packages/arui-scripts/src/configs/webpack.client.ts
- packages/arui-scripts/src/configs/webpack.server.ts
При попытке обновиться до RTK 2.0 столкнулся с ошибкой `(0 , redux_1.createStore) is not a function`. После небольшого исследования выяснил, что redux выпадал в assets, сборщик обрабатывал его как статику, а require('./node_modules/redux/dist/cjs/redux.cjs') при сборке возвращал строку 'assets/static/media/redux.a7cedf98.cjs' вместо модуля
Связано с тем, что с версии 5 в redux появился exports в package.json, и по умолчанию он ведет к `.cjs` файлу
Выяснил что в arui-script конфигах webpack есть функция `getExternalCodeLoader`, отвечающая за обработку node_modules. Добавление в неё `cjs` расширение исправляет проблему
> fix(configs/webpack): add cjs extension to getExternalCodeLoader

- .changeset/chatty-squids-kiss.md
- packages/arui-scripts-modules/README.md
- packages/arui-scripts-modules/global-definitions.d.ts
- packages/arui-scripts-modules/src/module-loader/__tests__/create-module-loader.tests.ts
- packages/arui-scripts-modules/src/module-loader/create-module-loader.ts
- packages/arui-scripts-modules/src/module-loader/utils/get-module.ts
- packages/arui-scripts/docs/modules.md
- packages/arui-scripts/src/configs/app-configs/types.ts
- packages/arui-scripts/src/configs/modules.ts
Некоторые микрофронты нашего проекта будут встраиваться в проекты других команд, некоторые из них находятся на очень старых версиях библиотек. Для корректной отработки таких ситуаций необходима поддержка и корректная обработка свойства shareScope - при загрузке модуля, а так же инициализации wmf плагина
> Поддержка свойства shareScope для модулей

- .changeset/strange-seas-wait.md
- packages/arui-scripts-modules/README.md
- packages/arui-scripts-modules/src/module-loader/create-module-loader.ts
- packages/arui-scripts-modules/src/module-loader/utils/__tests__/dom-utils.test.ts
- packages/arui-scripts-modules/src/module-loader/utils/__tests__/is-safari.test.ts
- packages/arui-scripts-modules/src/module-loader/utils/dom-utils.ts
- packages/arui-scripts-modules/src/module-loader/utils/fetch-resources.ts
- packages/arui-scripts-modules/src/module-loader/utils/is-safari.ts
Движок webkit (Safari) иначе обрабатывает инъекцию стилей, чем движок v8, вследствие чего, при медленном интернете и/или большом кол-ве микрофронтовых модулей, которые добавляют стили через link, может ломаться верстка загруженных модулей
Происходит это из-за того, что Safari ждёт полной загрузки файлов стилей перед тем как обновить CSSOM
Чтобы решить эту проблему предлагаю инжектить стили для Safari inline способом
На видео отображено как было и как стало. Был специально замедлен один из запросов загрузки стилей (колокольчик в шапке), чтобы наглядно отобразить проблему
https://github.com/user-attachments/assets/b063439f-1f2b-42fa-8e5a-f612b8a44470
https://github.com/user-attachments/assets/3de6f3ea-4235-4a4f-bbe7-75291b7d1de8
> feat(modules): fix inject style in safari

- .changeset/sweet-knives-punch.md
- packages/arui-scripts/src/configs/dev-server.ts
Исправлена работа clientOnly в дев режиме - теперь запросы на неизвестные адреса будут корректно фолбечится на index.html. В скомпиленном виде nginx и так корректно это делал, в дев режиме же мы получали 404
> fix(client-only): dev server history fallback for client only mode
